name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        plone-version: [4.3, 5.1]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - name: install virtualenv
      run: |
        pip install virtualenv==16.7.8
    - name: Run tests
      run: |
        PLONE_VERSION=${{matrix.plone-version}} make test
